using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Project_Euler
{
    /**
    * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    */
    public class Problem2 : Problem
    {
        public override double Solve(double variable)
        {
            int first = 0;
            int second = 1;
            double sum = 0;

            while(second < variable)
            {
                if (second % 2 == 0)
                {
                    sum += second;
                }

                int next = first + second;

                first = second;
                second = next;
            }

            return sum;
        }
    }
}
